// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwY_PAH_APKakuLrFY1cxegRorf0uflAU',
    appId: '1:966938261043:web:5e24091097786edbe29546',
    messagingSenderId: '966938261043',
    projectId: 'chat-app-5c9aa',
    authDomain: 'chat-app-5c9aa.firebaseapp.com',
    storageBucket: 'chat-app-5c9aa.firebasestorage.app',
    measurementId: 'G-DQEGBG5Y5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1o5blWHZNltSd-iT0E_z6BbbrLHG-iV4',
    appId: '1:966938261043:android:6425cd92fb1530cae29546',
    messagingSenderId: '966938261043',
    projectId: 'chat-app-5c9aa',
    storageBucket: 'chat-app-5c9aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wrH3PWrzeMbCNID3gqbp0dttCosjlVY',
    appId: '1:966938261043:ios:d97872f683c32f65e29546',
    messagingSenderId: '966938261043',
    projectId: 'chat-app-5c9aa',
    storageBucket: 'chat-app-5c9aa.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6wrH3PWrzeMbCNID3gqbp0dttCosjlVY',
    appId: '1:966938261043:ios:d97872f683c32f65e29546',
    messagingSenderId: '966938261043',
    projectId: 'chat-app-5c9aa',
    storageBucket: 'chat-app-5c9aa.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwY_PAH_APKakuLrFY1cxegRorf0uflAU',
    appId: '1:966938261043:web:2613dfe57d08fd07e29546',
    messagingSenderId: '966938261043',
    projectId: 'chat-app-5c9aa',
    authDomain: 'chat-app-5c9aa.firebaseapp.com',
    storageBucket: 'chat-app-5c9aa.firebasestorage.app',
    measurementId: 'G-LHQLZ6ZCTD',
  );
}
